#!/usr/bin/env bash
# /Applications/Mathematica.app/Contents/MacOS/WolframKernel -noprompt -initfile initkernel_pln.m -run 'ClientLibrary`Private`SlaveKernelPrivateStart["tcp://127.0.0.1:52817", "tcp://127.0.0.1:52818"]'
# Note: On any given installation, it is likely that that the WolframKernel
# will not automatically be in your path. You should modify your .bashrc
# or this file to make sure it is.
# Note: the port number 52817 is a magic number; it would probably
# be configurable, but this is a low priority. The same number
# will be found in the Mathemata CAS system.
# export PATH="$PATH:/Applications/Mathematica.app/Contents/MacOS"
#
# adding to the path should work, but because of trying to find
# some other library, I have to use the full path:
export WOLFRAM_KERNEL_LOCATION="/Applications/Mathematica.app/Contents/MacOS/WolframKernel"
pushd server
$WOLFRAM_KERNEL_LOCATION -noprompt -initfile ./server_scripts/initkernel_pln.m -run 'ClientLibrary`Private`SlaveKernelPrivateStart["tcp://127.0.0.1:52817", "tcp://127.0.0.1:52818"]' >> ../log/mathematica.log 2>&1
popd
